### ISSUE TITLE
Error while syncing contact

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-sync#121]
After updating my Sync app to 1.0.19, I got the following error in my logs (it makes the app crashes): 

```
PROPFIND /public/addressbooks/me/all-contacts/ 207 974.950 ms - -

/usr/local/cozy/apps/sync/build/server/models/contact.js:117
    bufferer = new stream.Writable;
               ^
TypeError: undefined is not a function
    at ClassFromGetModel.Contact.toVCF (/usr/local/cozy/apps/sync/build/server/models/contact.js:117:16)
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:96:24
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/cozy/apps/sync/node_modules/async/lib/async.js:134:13)
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:145:25
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:229:17
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:97:18
    at ClassFromGetModel.Contact.toVCF (/usr/local/cozy/apps/sync/build/server/models/contact.js:129:12)
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:96:24
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:227:13
```
